spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: Your Client Id
          clientSecret: Your client Secret
          scope:
           - email
           - profile
         github:
          clientId: Your Client Id
          clientSecret: Your client Secret
          scope:
           - email
           - user
